Change 20100721-hqm-m by hqm@new-host-5.home on 2010-07-21 23:39:51 EDT     in /Users/hqm/openlaszlo/trunk3     for http://svn.openlaszlo.org/openlaszlo/trunk
Summary: fix for " swf10 compiler errors not reported properly by LPS servlet"

New Features:

Bugs Fixed: LPP-9223

Technical Reviewer: max
QA Reviewer: max
Doc Reviewer: (pending)

Documentation:

Release Notes:

Overview:

SWF9External.java: the error collector class is not keeping track of the error 
object is creates in some cases
    

Details:
    

Tests:

test case from bug report now reports proper error the dev console when compiling
via browser/servlet

When compiling the attached test case, with lzr=swf10, you should see this error in the browser

 The application could not be compiled due to the following errors:
Compilation Errors
org.openlaszlo.sc.CompilerError: choke.lzx: 3: Error: The attribute final can only be used on a method defined in a class, in line: public static final function foo () {}



git-svn-id: http://svn.openlaszlo.org/openlaszlo/trunk@17057 fa20e4f9-1d0a-0410-b5f3-dc9c16b8b17c