Change 20081215-bargull-Dyr by bargull@dell--p4--2-53 on 2008-12-15 23:52:19     in /home/Admin/src/svn/openlaszlo/trunk     for http://svn.openlaszlo.org/openlaszlo/trunk
Summary: (lazy)replicator don't work in swf9

New Features:

Bugs Fixed: LPP-4667, LPP-7487

Technical Reviewer: ptw
QA Reviewer: henry
Doc Reviewer: (pending)

Documentation:

Release Notes:

Details:
The explicit replicator didn't work, esp. lz.lazyreplicator had some major problems.

LzNode: 
 VerifyError: Error #1068: LzDatapath and * cannot be reconciled 
Flash9 wanted to say it cannot cast objects, why ever this wasn't detected at compile time...

LzDataSelectionManager:
lz.replicator wants to be a fake LzReplicationManager, actually a mixin would be the right solution here..

replicator:
adjust getCloneForNode() to be compatible to lz.lazyreplicator

lazyreplicator:
update getCloneForNode() so it can be compiled for swf9

selection.lzx:
update testcase so it will work properly

    

Tests:
selection.lzx in swf8/swf9



git-svn-id: http://svn.openlaszlo.org/openlaszlo/trunk@12229 fa20e4f9-1d0a-0410-b5f3-dc9c16b8b17c