Change 20090613-raju-r by raju@Atlantia on 2009-06-13 23:52:31 CEST     in /Users/rajubitter/src/svn/openlaszlo/trunk     for http://rajubitter@svn.openlaszlo.org/openlaszlo/trunk
Summary: Add support for Flash Player's ability to switch to full screen mode for SWFx

New Features:

Bugs Fixed: LPP-8107

Technical Reviewer: max
QA Reviewer: (pending)
Doc Reviewer: (pending)

Documentation:
The documentation has to be updated, to reflect the new functionality.

Release Notes:
Works with Flash Player version 9.0.28. and all later versions.

Details:
http://jira.openlaszlo.org/jira/browse/LPP-8107

Embedding code
  lps/includes/sources/embednew.js
    + method lz.embed.swf
       - allowfullscreen: properties.allowfullscreen
  lps/includes/sources/flash.js
    + method lz.embed.dojo
      + added value to defaults: allowfullscreen: false
    + lz.embed.dojo.Embed.prototype.write
      object.html: added param/attribute allowFullScreen

LFC changes for all runtimes
  WEB-INF/lps/lfc/views/LaszloCanvas.lzs
    + @initarg allowfullscreen documentation added for fullscreen
    + public var allowfullscreen added
    + onfullscreen event added
    + public var fullscreen added
    + handling of @initarg allowfullscreen added to construct() method
    + Warning for runtimes that don't support fullscreen (DHTML) added to construct method
    + method function $lzc$set_fullscreen(fullscreen=true) added
    + callback method for fullscreen event added: function __fullscreenEventCallback (result:Boolean)
    + setter for allowfullscreen added function $lzc$set_allowfullscreen( fs:Boolean )
    + callback method for error reporting added __fullscreenErrorCallback(errorMessage)

SWF8 specific changes
  WEB-INF/lps/lfc/kernel/swf8/LzScreenKernel.as
    + Added method showFullScreen
    + Added handler method for fullScreenEvent fullScreenEventHandler: function(isFullScreen:Boolean){
  WEB-INF/lps/lfc/kernel/swf8/LzSprite.as
    + added allowfullscreen: true to capabilities

SWF9 specific changes
  WEB-INF/lps/lfc/kernel/swf9/LzScreenKernel.as
    + Added method showFullScreen
    + Added handler method for FullScreenEvent private static function fullScreenEventHandler(ev:FullScreenEvent) :void {
  WEB-INF/lps/lfc/kernel/swf9/LzSprite.as
    + added allowfullscreen: true to capabilities

DHTML specific changes
  WEB-INF/lps/lfc/kernel/swf9/LzSprite.as
    + added allowfullscreen: false to capabilities
    
Compiler (Java classes)
  WEB-INF/lps/server/src/org/openlaszlo/compiler/Canvas.java
    + private static final boolean DEFAULT_ALLOW_FULL_SCREEN = false;
    +  /** Fullscreen setting for canvas */
       private boolean mAllowFullscreen = false;
    + methods setAllowFullscreen() and isAllowFullscreen()
    + in method public String getXML(String content) {
      - added "allowfullscreen='" + isAllowFullscreen() + "' " + to buffer
  WEB-INF/lps/server/src/org/openlaszlo/compiler/Canvas.java
    + in method public void initializeFromElement(Canvas canvas, Element elt), handling of attribute allowfullscreen added

XSLT template files
  WEB-INF/lps/templates/html-response.xslt
  WEB-INF/lps/templates/app-console.xslt
    + added allowFullScreen: '<xsl:value-of select="/canvas/@fullscreen"/>' to lz.embed.dhtml({})

Tests:
  + test/fullscreen/fullscreentest_allowfullscreen_false.lzx
Test file for a canvas with allowfullscreen="false", should output error method for each runtime.

 + test/fullscreen/fullscreentest_embed_missing_allowfullscreen.html
The embed code with the allowFullScreen param set to false. Will show the following error message when trying to switch to fullscreen:
  ERROR: Flash Player Security Error Error #2152
  Usage of fullscreen feature is supported starting with Flash Player 9,0,28,0.
  You are currently using Flash Player 10.22 
  ERROR: Check your SWF embed code for missing param tag <param name="allowFullScreen" value="true" /> inside the <object> tag,
  or missing attribute allowFullScreen="true" in <embed> tag.
  canvas.showFullScreen() can be called only in response to a mouse click or keypress.
 
test/fullscreen/fullscreentest_working_SWF8_SWF9.lzx
This should work for SWFx and show a warning at startup for DHTML, and an error message if you try to go into fullscreen mode.



git-svn-id: http://svn.openlaszlo.org/openlaszlo/trunk@14192 fa20e4f9-1d0a-0410-b5f3-dc9c16b8b17c