Change 20070208-ptw-x by ptw@dueling-banjos.local on 2007-02-08 19:29:46 EST     in /Users/ptw/OpenLaszlo/trunk
Summary: Binary Library tweaks

Bugs Fixed:
LPP-NaN: Compiler chokes if library.lzx does not exist, even if
library.lzo does
LPP-NaN: Compiler does not recompile app if library.lzo changes

Technical Reviewer: henry (pending)
QA Reviewer: pablo (pending)
Doc Reviewer: n/a

Details:
    lzx.rnc: Add private `includes` attribute to `<library>` tag, used
    for binary libraries to record the includes that they included.

    Main, CSSHandler: Remove printStackTrace calls, now that we know about
    --onerror throw

    CompilationManager: add flag for resolving Library files.

    LibraryCompiler, Parser: remove redundant resolveLibraryName,
    process `includes` attribute.

    ToplevelCompiler, SWFWriter: Use new CompilationEnvironment.resolveLibrary
    method, enhance getLibraries to be able to get back the
    auto-include and visited sets.

    LibraryWriter: Learn to write out the `includes` attribute (list
    of all includes that this binary library represents), make
    compression and obfuscation controllable from command line (for
    debugging).

    FileResolver: Add an option to resolve using the 'library rules'
    (if a directory is passed add library.lzx, look for library.lzo
    first).

    CompilationEnvironment: Add new resolveLibrary method, let
    resolveReference take a third argument specifying library
    resolution, default to element being an include element.

    ImportCompiler, Parser: resolve as library.

    Compiler: Pass application file and root element to LibraryWriter.

    StyleSheetCompiler: use environment resolve interface, give
    location info for stylesheet script, ensure stylesheet script is
    emitted as a statement.

    CompilationError: careful about null.

Tests:
    henry's simple library test
    smokecheck
    pablo's library compiles and loads, but does not run (yet)

git-svn-id: http://svn.openlaszlo.org/openlaszlo/trunk@3791 fa20e4f9-1d0a-0410-b5f3-dc9c16b8b17c