Change 20100601-hqm-c by hqm@badtzmaru.home on 2010-06-01 14:59:03 EDT     in /Users/hqm/openlaszlo/trunk     for http://svn.openlaszlo.org/openlaszlo/trunk
Summary:  better error reporting from compiler when using debug eval

New Features:

Bugs Fixed: LPP-9061

Technical Reviewer: ptw
QA Reviewer: (pending)
Doc Reviewer: (pending)

Documentation:

Release Notes:

Overview:
    

Details:
    

Tests:

debug eval of a function expression returns a compiler error instead of silent failure

test case below, Note that this ought the be a legal expression and
not get a compilation error, but there's another bug causing the free
reference to global 'canvas' to be regarded as undefined. But given that it does
generate a compile error, it is reported to the user.

lzx> (function (x) {return canvas})()  
'Parse error: org.openlaszlo.sc.CompilerError: line unknown: Error: Access of undefined property canvas, in line: return canvas\nline unknown: Error: Access of undefined property Error, in line: if ($lzsc$e is Error && $lzsc$e !== lz["$lzsc$thrownError"]) {\nline unknown: Error: Access of undefined property lz, in line: if ($lzsc$e is Error && $lzsc$e !== lz["$lzsc$thrownError"]) {\nline unknown: Error: Access of undefined property $lzsc$runtime, in line: $lzsc$runtime.$reportException("[CommonGenerator.parseFragment]", 2, $lzsc$e)' 
lzx> 




git-svn-id: http://svn.openlaszlo.org/openlaszlo/trunk@16597 fa20e4f9-1d0a-0410-b5f3-dc9c16b8b17c