Change 20080528-hqm-M by hqm@badtzmaru.home on 2008-05-28 10:57:11 EDT     in /Users/hqm/openlaszlo/trunk4     for http://svn.openlaszlo.org/openlaszlo/trunk
Summary: make better compiler error for missing dataset name attribute

New Features:

Bugs Fixed: LPP-6052

Technical Reviewer: ptw
QA Reviewer: (pending)
Doc Reviewer: (pending)

Documentation:

Release Notes:

Details:
    
throw a real CompilationError with element info


Tests:

compiler test case in bug, get  file and line info:

    badtzmaru:trunk4 hqm$ lzc test/ca.lzx
    Compiling: test/ca.lzx to test/ca.lzr=swf8.swf
    Compilation errors occurred:
    ../../test/libby.lzx:3:24: name is a required attribute of dataset




git-svn-id: http://svn.openlaszlo.org/openlaszlo/trunk@9349 fa20e4f9-1d0a-0410-b5f3-dc9c16b8b17c