Change 20090905-sebastianwagner-d by sebastianwagner@sebastian-wagners-macbook-pro.local on 2009-09-05 19:32:56 CEST     in /Users/sebastianwagner/Documents/work/openlaszlo/branches/openlaszlo/trunk     for http://svn.openlaszlo.org/openlaszlo/trunk
Summary: This Fixes: LPP-8437, LPP-8029
Extends Output of RPC with Gson as marshaller. This changeset adds a new Factory Class to set a custom Json Marshaller 
LZJsonFactory => to overwrite the default Json Handling you can call the Method: LZJsonFactory.setJsonBuilderInstance(LZBaseJsonMarshallAdapter instance)

There are two implementations of Json:
1) The existing, that I slightly refactored to fit into the Factory + Adapter/Interface Pattern (LZJsonMarshaller)
2) The Gson Handling which is now the default one (LZGsonMarshaller)

To write your own Marshaller you have to use the pattern
public MyMarshaller extends LZBaseJsonMarshallAdapter implements ILZJsonMarshaller {
	public synchronized byte[] createObject(Object object, String objectReturnType) {}
}
and then set and instance of that Object with LZJsonFactory.setJsonBuilderInstance(myMarshallerInstanceObject)

The LZGsonMarshaller has some default settings to make the JSon Output 100% equal to the existing one.
To disable that you should call:
LZGsonMarshaller.applyLzDefaultGsonProperties = false;

To get the Gson Factory to set your custom Marhsalling Options you have to:
GsonBuilder gsonBuilder = LZGsonMarshaller.getGsonBuilderInstance()
=> using the gsonBuilder you then can set any property that is documentated at:
http://sites.google.com/site/gson/gson-user-guide

By using Gson you can then also use annotations or other manipulations to modify the JSon output.

If Gson detects a Circular Reference it will throw for example:
ava.lang.IllegalStateException: Circular reference found: org.i4change.app.hibernate.beans.user.Users@2855f16e                                                         
        at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:108)                                                                                             
        at com.google.gson.JsonSerializationVisitor.getJsonElementForChild(JsonSerializationVisitor.java:117)                                                           
        at com.google.gson.JsonSerializationVisitor.addAsChildOfObject(JsonSerializationVisitor.java:95)     
....

New Features:

Bugs Fixed: LPP-8437, Lpp-8029

Technical Reviewer: hqm
QA Reviewer: (pending)
Doc Reviewer: (pending)

Documentation:

Release Notes:

Details:
    

Tests:



git-svn-id: http://svn.openlaszlo.org/openlaszlo/trunk@14689 fa20e4f9-1d0a-0410-b5f3-dc9c16b8b17c