Change 20080821-Philip-0 by Philip@Philip-DC on 2008-08-21 14:11:21 EDT      in /cygdrive/f/laszlo/svn/src/svn/openlaszlo/trunk      for http://svn.openlaszlo.org/openlaszlo/trunk
Summary: Fix swf9 error that causes blank address forms in Amazon

New Features:

Bugs Fixed: LPP-6866

Technical Reviewer: hqm
QA Reviewer: (pending)
Doc Reviewer: (pending)

Documentation:

Release Notes:

Details:
The blank form is caused by a swf9 error. You can see it by using the debug flash9 player. When you create a new address, an anonymous dataset is used. When you try and edit a real dataset, the code expects AnonDatasetGenerator to have an additional variable. The error is:

ReferenceError: Error #1069: Property __LZdepChildren not found on .AnonDatasetGenerator and there is no default value.

The fix is to define the variable in AnonDatasetGenerator.


Tests:
 From LPP-6866:
   Open Checkout tab
   Add new address
   Select OK
   Click edit in new address
   Result: Blank pane

The amazon app now shows the shipping address form.

Files:
M      WEB-INF/lps/lfc/data/LzParsedPath.lzs

Changeset: http://svn.openlaszlo.org/openlaszlo/patches/20080821-Philip-0.tar


git-svn-id: http://svn.openlaszlo.org/openlaszlo/trunk@10736 fa20e4f9-1d0a-0410-b5f3-dc9c16b8b17c