Change 20090128-hqm-P by hqm@badtzmaru.home on 2009-01-28 08:51:51 EST     in /Users/hqm/openlaszlo/trunk-clean     for http://svn.openlaszlo.org/openlaszlo/trunk
Summary:  compilation errors in imported libraries

New Features:

Bugs Fixed: LPP-7689

Technical Reviewer: promanik
QA Reviewer: (pending)
Doc Reviewer: (pending)

Documentation:

Release Notes:

Details:
    
+ since we now reuse the same directory for compiling libraries, we need to delete
the "app.swf" file before compiling, otherwise the logic in the SWF9External script compiler
thinks that the compile succeeded and won't report errors.


Tests:

compile test case in LPS server (swf9 runtime) , see compiler errors in
web page properly displayed

Compilation Errors
org.openlaszlo.sc.CompilerError: lib1.lzx: 4: Error: Incompatible override, in line: static var tagname = "ghcls1";static var attributes = new LzInheritedHash($lzc$class_ghcls0.attributes);override function testMethod ($1) {




git-svn-id: http://svn.openlaszlo.org/openlaszlo/trunk@12675 fa20e4f9-1d0a-0410-b5f3-dc9c16b8b17c