Change 20071015-ben-j by ben@slim.local on 2007-10-15 11:27:27 PDT     in /Users/ben/src/svn/openlaszlo/trunk     for http://svn.openlaszlo.org/openlaszlo/trunk
Summary: Make sure that lfc.lzx gets added to the distro

Technical Reviewer: minsky
QA Reviewer: mkratt

Documentation:
The file lfc.lzx was added to the schema directory. It needs to be in
schema/ when live code looks for it. In particular, laszlo-explorer
looks for it. Without this fix, the nightly deployment of trunk is broken, 
with this error:
Error: home/laszlo/opt/apache-tomcat-5.5.23-labs/webapps/trunk-nightly/laszlo-explorer/explore-nav.lzx: file not found: /home/laszlo/opt/apache-tomcat-5.5.23-labs/webapps/trunk-nightly/WEB-INF/lps/schema/lfc.lzx (No such file or directory)

This change makes sure the lfc.lzx file is tucked into the distro. 

Tests:
Run a nightly build of trunk, deploy it, visit
http://labs.openlaszlo.org/trunk-nightly/laszlo-explorer/index.jsp?lzr=swf7
and the left-nav should work. 



git-svn-id: http://svn.openlaszlo.org/openlaszlo/trunk@6845 fa20e4f9-1d0a-0410-b5f3-dc9c16b8b17c