Change 20080828-hqm-s by hqm@badtzmaru.home on 2008-08-28 22:46:43 EDT     in /Users/hqm/openlaszlo/trunk     for http://svn.openlaszlo.org/openlaszlo/trunk
Summary: swf9 cursor bug

New Features:

Bugs Fixed:

Technical Reviewer: max
QA Reviewer: pbr
Doc Reviewer: (pending)

Documentation:

Release Notes:

Details:
    
sprite.clickbutton may be null, so check before dereferencing


Tests:

run test/swf9/hello.lzx in swf9, click on the text which says "I am clickable text", verify
that this runtime error does not occur:

 TypeError: Error #1009: Cannot access a property or method of a null object reference.
	 at LzSprite/__mouseEvent()[/private/tmp/lzswf9/lzgen25836/LzSprite.as:344]




git-svn-id: http://svn.openlaszlo.org/openlaszlo/trunk@10840 fa20e4f9-1d0a-0410-b5f3-dc9c16b8b17c