Change 20100603-hqm-h by hqm@badtzmaru.home on 2010-06-03 19:48:16 EDT     in /Users/hqm/openlaszlo/trunk2     for http://svn.openlaszlo.org/openlaszlo/trunk
Summary: update to flex compiler milestone release version flex_sdk_4.0.0.14159

New Features:

Bugs Fixed: LPP-9081

Technical Reviewer: ptw
QA Reviewer: max
Doc Reviewer: (pending)

Documentation:

Release Notes:

Overview:
    
update flex compiler files to match milestone release version flex_sdk_4.0.0.14159


Details:

skip-pre-commit-checks

    
I had to add a flag to the call to the flex compiler:
      -static-link-runtime-shared-libraries

otherwise I get this link warning when compiling

Stray error string from external compiler: /private/var/folders/xh/xhmdrA41HCKjjiditeqN1k+++TI/-Tmp-/lzswf9/build/edit/LzPreloader.as: Warning: This compilation unit did not have a factoryClass specified in Frame metadata to load the configured runtime shared libraries. To compile without runtime shared libraries either set the -static-link-runtime-shared-libraries option to true or remove the -runtime-shared-libraries option.

And this runtime error from the player when loading an app

VerifyError: Error #1014: Class mx.core::MovieClipLoaderAsset could not be found.

	At flash.display::MovieClip/nextFrame()
	at LzPreloader/enterFrame()[/Users/hqm/openlaszlo/lib/jakarta-tomcat-5.0.30/temp/lzswf9/Users/hqm/openlaszlo/trunk2/test/tlf/build/edit/LzPreloader.as:20]


This changeset includes a new directory in the flex directory, framework/rsls, which contains runtime shared libraries
in some new archives format from adobe, ".swz".  

There's documentation on how to publish the text layout framework
runtime shared libraries in
http://help.adobe.com/en_US/flash/cs/using/WSb03e830bd6f770ee-4b0db644124bbdb363d-8000.html#WSb03e830bd6f770ee72b69dc71257a25aa72-8000
if we figure out how to run without static linking.

+ We have a patched version of the flex compiler command shell, fcsh, which is modified to call lzx
in incremental mode. We don't have the whole flex compiler source tree under our own 
version control, but I have the patch to this file saved in a tar file vendor/lzc-fcsh.tgz, and have updated it
and recompiled for this new flex build.



Tests:

smokecheck in swf10
component sampler in swf10
lzpix in swf10

test cases that use new TLF classes, in test/tlf



git-svn-id: http://svn.openlaszlo.org/openlaszlo/trunk@16606 fa20e4f9-1d0a-0410-b5f3-dc9c16b8b17c